# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

lgbm.data.create <- function(x, params = "num_model_predict=-1") {
    .Call('RLightGBM_RLGBM_CreateDatasetFromMat', PACKAGE = 'RLightGBM', x, params)
}

