# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

lgbm.data.create <- function(x, params = "num_iteration_predict=-1") {
    .Call('_RLightGBM_RLGBM_CreateDatasetFromMat', PACKAGE = 'RLightGBM', x, params)
}

lgbm.data.create.CSR <- function(i, p, x, dim, params = "num_iteration_predict=-1") {
    .Call('_RLightGBM_RLGBM_CreateDatasetFromCSR', PACKAGE = 'RLightGBM', i, p, x, dim, params)
}

lgbm.data.create.CSC <- function(i, p, x, dim, params = "num_iteration_predict=-1") {
    .Call('_RLightGBM_RLGBM_CreateDatasetFromCSC', PACKAGE = 'RLightGBM', i, p, x, dim, params)
}

lgbm.data.setField <- function(data_handle, field_name, x) {
    invisible(.Call('_RLightGBM_RLGBM_DatasetSetField', PACKAGE = 'RLightGBM', data_handle, field_name, x))
}

lgbm.booster.create.str <- function(data_handle, params = "task=train") {
    .Call('_RLightGBM_RLGBM_CreateBoosterFromString', PACKAGE = 'RLightGBM', data_handle, params)
}

lgbm.booster.create <- function(data_handle, config) {
    .Call('_RLightGBM_RLGBM_CreateBooster', PACKAGE = 'RLightGBM', data_handle, config)
}

lgbm.booster.load <- function(filename) {
    .Call('_RLightGBM_RLGBM_CreateBoosterFromFile', PACKAGE = 'RLightGBM', filename)
}

lgbm.booster.train <- function(booster_handle, num_iters) {
    invisible(.Call('_RLightGBM_RLGBM_TrainBooster', PACKAGE = 'RLightGBM', booster_handle, num_iters))
}

lgbm.booster.predict <- function(booster_handle, x, predict_type = 0L, num_used_iterations = -1L) {
    .Call('_RLightGBM_RLGBM_PredictFromMat', PACKAGE = 'RLightGBM', booster_handle, x, predict_type, num_used_iterations)
}

lgbm.booster.predict.CSR <- function(booster_handle, i, p, x, dim, predict_type = 0L, num_used_iterations = -1L) {
    .Call('_RLightGBM_RLGBM_PredictFromCSR', PACKAGE = 'RLightGBM', booster_handle, i, p, x, dim, predict_type, num_used_iterations)
}

lgbm.booster.save <- function(booster_handle, filename, num_used_iterations = -1L) {
    invisible(.Call('_RLightGBM_RLGBM_SaveBoosterModel', PACKAGE = 'RLightGBM', booster_handle, filename, num_used_iterations))
}

lgbm.booster.dump <- function(booster_handle, num_iteration = -1L) {
    .Call('_RLightGBM_RLGBM_DumpBoosterModel', PACKAGE = 'RLightGBM', booster_handle, num_iteration)
}

