// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/RLightGBM.h"
#include <Rcpp.h>

using namespace Rcpp;

// RLGBM_CreateDatasetFromMat
SEXP RLGBM_CreateDatasetFromMat(NumericMatrix x, CharacterVector params);
RcppExport SEXP RLightGBM_RLGBM_CreateDatasetFromMat(SEXP xSEXP, SEXP paramsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type params(paramsSEXP);
    rcpp_result_gen = Rcpp::wrap(RLGBM_CreateDatasetFromMat(x, params));
    return rcpp_result_gen;
END_RCPP
}
